version: "3"

services:
  express:
    build: apps/express
    env_file: apps/express/.env
    container_name: express
    ports:
      - "3000:3000"
    networks:
      - local_network
  firsthop:
    build: apps/backendservice_firsthop
    env_file: apps/backendservice_firsthop/.env
    container_name: firsthop
    ports:
      - "3001:3001"
    depends_on:
      - express
      - secondhop
    networks:
      - local_network
  secondhop:
    build: apps/backendservice_secondhop
    env_file: apps/backendservice_secondhop/.env
    container_name: secondhop
    ports:
      - "3002:3002"
    networks:
      - local_network
networks:
  local_network:
    driver: host